# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Carlo Valentin'
tagline:             ''
description:         'I am Carlo Valentin. I break things for a living. In my spare time I save virtual worlds and play electronic music.'
url:                 http://carlovalentin.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Carlo Valentin
  email:             contact@carlovalentin.com

# Custom vars
version:             1.0.0
