# Site settings
title: Carlo Valentin
email: blog@carlovalentin.com
sidebar: "Breaking things by day, saving virtual worlds by night."
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://cvalentin.github.io" # the base hostname & protocol for your site
twitter_username: carlo_valentin
github_username:  cvalentin
permalink: /:categories/:title
# Build settings
markdown: kramdown

paginate: 4

author: Carlo Valentin

gems: [jekyll-paginate]

